global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  # - job_name: "prometheus"
  #   scrape_interval: 5s
  #   static_configs:
  #   - targets: ["localhost:9090"]

  # - job_name: "otel-collector"
  #   scrape_interval: 5s
  #   static_configs:
  #   - targets: ["otel-collector:9464"]
  #   # - targets: ["localhost:8888"]
  
  - job_name: aggregated-trace-metrics
    static_configs:
    - targets: ['otel-collector:8889']

  # - job_name: "node"
  #   static_configs:
  #   - targets: ["node-exporter:9100"]

# remote_write:
#   - url: "<Your Prometheus remote_write endpoint>"
#     basic_auth:
#       username: "<Your Grafana Username>"
#       password: "<Your Grafana API key>"